name: CSV File Validator

on:
  push:
    branches:
      - main

jobs:
  validate-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run read secret program
        env:
          USERNAME_ENV: ${{ secrets.USERNAME }}
          PASSWORD_ENV: ${{ secrets.PASSWORD }}
        run: python3 read.py